In [1]:
from bs4 import BeautifulSoup
with open('CMExport_LCAIE10015_Mohandseen_10.97.111.18_2020031405.xml', 'r') as f: 
    data = f.read()
Bs_data = BeautifulSoup(data, "lxml")

In [2]:
from xml.dom import minidom
mydoc = minidom.parse('CMExport_LCAIE10015_Mohandseen_10.97.111.18_2020031405.xml')
MO = mydoc.getElementsByTagName('MO')

In [3]:
import re
import pandas as pd
import time
r4=list()
data = {
        'Element':[],
        'Parameter':[],
        'Value':[]}

Main_DF=pd.DataFrame(data)

for Object in range(1,MO.length):
    Site_Element_Name = MO[Object].attributes['fdn'].value
    Site_Element_Data = Bs_data.find('mo', {'fdn':Site_Element_Name})
    r1=re.findall(r'<attr name="(.*?)</attr>',str(Site_Element_Data.find_all('attr')))
    fdn=r1[0].replace('fdn">','')
    del(r1[0])
    r2 = str(r1).split(',')
    
    for i in range (0,len(r2)):
        if '">' and not '=' in r2[i]:
            spliter=str(r2[i]).split('">')
            r4.append(spliter)
        elif '">' and '=' in r2[i]:
            spliter=str(r2[i]).split('=')
            r4.append(spliter)
        elif '=' and not '">' in r2[i]:
            spliter=str(r2[i]).split('=')
            r4.append(spliter)
    
    
    df=pd.DataFrame(r4,columns=['Para','Val'])
    df['Parameter']=df['Para'].str.replace("'", '').str.replace("[", '')
    df['Value']=df['Val'].str.replace("'", '').str.replace("]", '')
    df['Element']=fdn
    final_temp_DF=df.drop(['Para', 'Val'], axis=1)
    Main_DF=Main_DF.append(final_temp_DF,ignore_index=True)
    r4.clear()

C:\Users\asrar\Anaconda3\lib\site-packages\pandas\core\frame.py:7123: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  sort=sort,

In [4]:
Main_DF

,Element,Parameter,Value
0,"NE=1278,eNodeBBBP=0_3_0",CN,0
1,"NE=1278,eNodeBBBP=0_3_0",MOIndex,1023_0_0_3
2,"NE=1278,eNodeBBBP=0_3_0",SN,3
3,"NE=1278,eNodeBBBP=0_3_0",SRN,0
4,"NE=1278,eNodeBBBP=0_3_0",TYPE,UBBP
...,...,...,...
53579,"NE=1278,eNodeBX2INTERFACE=40934",X2INTERFACEID,40934
53580,"NE=1278,eNodeBX2INTERFACE=40934",className,BTS3900X2INTERFACE
53581,"NE=1278,eNodeBX2INTERFACE=40934","name"">eNodeB Function Name",LCAIE10015_Mohandseen
53582,"NE=1278,eNodeBX2INTERFACE=40934",X2Interface ID,40934
53583,"NE=1278,eNodeBX2INTERFACE=40934",neID,1023

In [15]:
Site_Name=df[['Value']].loc[df['Parameter'] == 'ENODEBFUNCTIONNAME']
Site_Name

                   Value
0  LCAIE10015_Mohandseen

In [16]:
Main_DF['Site']=str(Site_Name).replace('                   Value\n0  ','')+'/'+Main_DF['Element']

In [17]:
Main_DF

,Element,Parameter,Value,Site
0,"NE=1278,eNodeBBBP=0_3_0",CN,0,"LCAIE10015_Mohandseen/NE=1278,eNodeBBBP=0_3_0"
1,"NE=1278,eNodeBBBP=0_3_0",MOIndex,1023_0_0_3,"LCAIE10015_Mohandseen/NE=1278,eNodeBBBP=0_3_0"
2,"NE=1278,eNodeBBBP=0_3_0",SN,3,"LCAIE10015_Mohandseen/NE=1278,eNodeBBBP=0_3_0"
3,"NE=1278,eNodeBBBP=0_3_0",SRN,0,"LCAIE10015_Mohandseen/NE=1278,eNodeBBBP=0_3_0"
4,"NE=1278,eNodeBBBP=0_3_0",TYPE,UBBP,"LCAIE10015_Mohandseen/NE=1278,eNodeBBBP=0_3_0"
...,...,...,...,...
53579,"NE=1278,eNodeBX2INTERFACE=40934",X2INTERFACEID,40934,"LCAIE10015_Mohandseen/NE=1278,eNodeBX2INTERFAC..."
53580,"NE=1278,eNodeBX2INTERFACE=40934",className,BTS3900X2INTERFACE,"LCAIE10015_Mohandseen/NE=1278,eNodeBX2INTERFAC..."
53581,"NE=1278,eNodeBX2INTERFACE=40934","name"">eNodeB Function Name",LCAIE10015_Mohandseen,"LCAIE10015_Mohandseen/NE=1278,eNodeBX2INTERFAC..."
53582,"NE=1278,eNodeBX2INTERFACE=40934",X2Interface ID,40934,"LCAIE10015_Mohandseen/NE=1278,eNodeBX2INTERFAC..."
53583,"NE=1278,eNodeBX2INTERFACE=40934",neID,1023,"LCAIE10015_Mohandseen/NE=1278,eNodeBX2INTERFAC..."

In [18]:
Final_Main_DF = Main_DF.drop(['Element'], axis=1)

In [19]:
Final_Main_DF

,Parameter,Value,Site
0,CN,0,"LCAIE10015_Mohandseen/NE=1278,eNodeBBBP=0_3_0"
1,MOIndex,1023_0_0_3,"LCAIE10015_Mohandseen/NE=1278,eNodeBBBP=0_3_0"
2,SN,3,"LCAIE10015_Mohandseen/NE=1278,eNodeBBBP=0_3_0"
3,SRN,0,"LCAIE10015_Mohandseen/NE=1278,eNodeBBBP=0_3_0"
4,TYPE,UBBP,"LCAIE10015_Mohandseen/NE=1278,eNodeBBBP=0_3_0"
...,...,...,...
53579,X2INTERFACEID,40934,"LCAIE10015_Mohandseen/NE=1278,eNodeBX2INTERFAC..."
53580,className,BTS3900X2INTERFACE,"LCAIE10015_Mohandseen/NE=1278,eNodeBX2INTERFAC..."
53581,"name"">eNodeB Function Name",LCAIE10015_Mohandseen,"LCAIE10015_Mohandseen/NE=1278,eNodeBX2INTERFAC..."
53582,X2Interface ID,40934,"LCAIE10015_Mohandseen/NE=1278,eNodeBX2INTERFAC..."
53583,neID,1023,"LCAIE10015_Mohandseen/NE=1278,eNodeBX2INTERFAC..."

In [20]:
Final_Main_DF = Final_Main_DF[['Site','Parameter','Value']]

In [21]:
Final_Main_DF

,Site,Parameter,Value
0,"LCAIE10015_Mohandseen/NE=1278,eNodeBBBP=0_3_0",CN,0
1,"LCAIE10015_Mohandseen/NE=1278,eNodeBBBP=0_3_0",MOIndex,1023_0_0_3
2,"LCAIE10015_Mohandseen/NE=1278,eNodeBBBP=0_3_0",SN,3
3,"LCAIE10015_Mohandseen/NE=1278,eNodeBBBP=0_3_0",SRN,0
4,"LCAIE10015_Mohandseen/NE=1278,eNodeBBBP=0_3_0",TYPE,UBBP
...,...,...,...
53579,"LCAIE10015_Mohandseen/NE=1278,eNodeBX2INTERFAC...",X2INTERFACEID,40934
53580,"LCAIE10015_Mohandseen/NE=1278,eNodeBX2INTERFAC...",className,BTS3900X2INTERFACE
53581,"LCAIE10015_Mohandseen/NE=1278,eNodeBX2INTERFAC...","name"">eNodeB Function Name",LCAIE10015_Mohandseen
53582,"LCAIE10015_Mohandseen/NE=1278,eNodeBX2INTERFAC...",X2Interface ID,40934
53583,"LCAIE10015_Mohandseen/NE=1278,eNodeBX2INTERFAC...",neID,1023

In [22]:
Final_Main_DF.to_csv(r'{}.csv'.format(str(Site_Name).replace('                   Value\n0  ','')), index = False)